import ("csv", "file", "db_after_insert.fx").

# Imports the fact file generated by api_insert.fx. Update rewrites facts only;
# procedures stay in command/source files.

UpdateCustomer(input: row) =>
    c := row,
    where c.id == "c004",
    return (
        id: c.id,
        name: c.name,
        city: c.city,
        total: c.total,
        status: c.status,
        tier: "gold"
    )
else
    return (
        id: c.id,
        name: c.name,
        city: c.city,
        total: c.total,
        status: c.status,
        tier: c.tier
    ).

UpdatedCustomer(input: row) =>
    c := row,
    where c.id == "c004",
    return (
        id: c.id,
        tier: "gold"
    ).

main() =>
    updatedRows := lambda(Customer, c => UpdateCustomer(input: c)),
    changedRows := lambda(Customer, c => UpdatedCustomer(input: c)),
    factText := csv.toFelidaeFacts(data: updatedRows, type: "Customer"),
    writeStatus := file.writeFile(
        path: "examples/fact_api/db_after_update.fx",
        data: factText,
        mode: "write"
    ),
    return (
        updated_count: count(updatedRows),
        changed_count: count(changedRows),
        db_file: "examples/fact_api/db_after_update.fx",
        write: writeStatus,
        facts: factText
    ).
