import ("csv" "file" "db_after_update.fx").

# Imports the fact file generated by api_update.fx. Delete means rewriting the
# next fact store without rows matching delete conditions.

KeepCustomer(input: row) =>
    c := row,
    where c.status != "inactive",
    return (
        id: c.id,
        name: c.name,
        city: c.city,
        total: c.total,
        status: c.status,
        tier: c.tier
    ).

DeleteCandidate(input: row) =>
    c := row,
    where c.status == "inactive",
    return (
        id: c.id,
        reason: "inactive"
    ).

main() =>
    keptRows := lambda(Customer, c => KeepCustomer(input: c)),
    deletedRows := lambda(Customer, c => DeleteCandidate(input: c)),
    factText := csv.toFelidaeFacts(data: keptRows, type: "Customer"),
    writeStatus := file.writeFile(
        path: "examples/fact_api/db_after_delete.fx",
        data: factText,
        mode: "write"
    ),
    return (
        kept_count: count(keptRows),
        deleted_count: count(deletedRows),
        db_file: "examples/fact_api/db_after_delete.fx",
        write: writeStatus,
        deleted: deletedRows,
        facts: factText
    ).
