main() =>
    return (
        minimum: MIN(0.8, 0.3),
        maximum: MAX(0.8, 0.3),
        absolute: ABS(-4.5),
        difference: DIFF(8.2, 5.0),
        average: AVG(10, 20),
        weightedAverage: WEIGHTED_AVG(10, 20, 1, 3),
        clamped: CLAMP(1.4, 0, 1),
        floor: FLOOR(4.8),
        ceil: CEIL(4.2),
        rounded: ROUND(4.6),
        truncated: TRUNC(4.8),
        squareRoot: SQRT(9),
        cubeRoot: CBRT(8),
        power: POW(2, 3),
        exponential: EXP(0),
        naturalLog: LOG(1),
        decimalLog: LOG10(1000),
        modulo: MOD(7.5, 2),
        interpolated: LERP(10, 20, 0.25),
        sign: SIGN(-7.2),
        reciprocal: RECIPROCAL(4),
        square: SQUARE(3),
        cube: CUBE(2),
        inRange: IN_RANGE(0.7, 0, 1),
        finite: IS_FINITE(1.5),
        nan: IS_NAN(1.5)
    )
