# Set mathematics is dispatched directly by the AST interpreter.

def Set.union(sets: array) => ()
def Set.intersection(sets: array) => ()
def Set.intersectionBy(sets: array, fields: array) => ()
def Set.difference(sets: array) => ()
def Set.differenceBy(sets: array, fields: array) => ()
def Set.symmetricDifference(sets: array) => ()
def Set.symmetricDifferenceBy(sets: array, fields: array) => ()
def Set.equals(sets: array) => ()
def Set.equalsBy(sets: array, fields: array) => ()
def Set.subset(sets: array) => ()
def Set.subsetBy(sets: array, fields: array) => ()
def Set.superset(sets: array) => ()
def Set.disjoint(sets: array) => ()
def Set.disjointBy(sets: array, fields: array) => ()
def Set.cardinality(set: any) => ()
def Set.contains(set: any, value: any) => ()
def Set.containsBy(set: any, value: any, fields: array) => ()
