# Set mathematics is direct Builtin IR executed by RegisterVm.

Set.union(sets: array) => ()
Set.intersection(sets: array) => ()
Set.intersectionBy(sets: array, fields: array) => ()
Set.difference(sets: array) => ()
Set.differenceBy(sets: array, fields: array) => ()
Set.symmetricDifference(sets: array) => ()
Set.symmetricDifferenceBy(sets: array, fields: array) => ()
Set.equals(sets: array) => ()
Set.equalsBy(sets: array, fields: array) => ()
Set.subset(sets: array) => ()
Set.subsetBy(sets: array, fields: array) => ()
Set.superset(sets: array) => ()
Set.disjoint(sets: array) => ()
Set.disjointBy(sets: array, fields: array) => ()
Set.cardinality(set: any) => ()
Set.contains(set: any, value: any) => ()
Set.containsBy(set: any, value: any, fields: array) => ()
