system.flibrary.csv.parse(data: string) => ()
system.flibrary.csv.toFacts(data: string, type: string) => ()
system.flibrary.csv.toText(data: array) => ()
system.flibrary.csv.toFelidaeFacts(data: array, type: string) => ()
system.flibrary.csv.addRow(data: array, row: any) => ()
system.flibrary.csv.findRows(data: array, key: string, value: any) => ()
system.flibrary.csv.updateRows(data: array, key: string, value: any, patch: any) => ()
system.flibrary.csv.deleteRows(data: array, key: string, value: any) => ()
