filetype.felidae.description=Felidae source file
action.felidae.check.text=Check Felidae File
action.felidae.check.description=Check the current file using Celidae
action.felidae.run.text=Run Felidae File
action.felidae.run.description=Run the current Felidae source file
action.felidae.visualize.text=Visualize Felidae Data Graph
action.felidae.visualize.description=Inspect the current file using Celidae visual analytics
toolwindow.felidae.title=Felidae
