name = "Felidae"
grammar = "felidae"
path_suffixes = ["fx"]
line_comments = ["# "]
autoclose_before = ",)]}"
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
