#include "FelidaeGrammar.h"

#include <sentencepiece_model.pb.h>
#include <sentencepiece_processor.h>
#include <sentencepiece_trainer.h>

#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
class CorpusIterator final : public sentencepiece::SentenceIterator {
public:
    explicit CorpusIterator(const std::vector<std::string>& corpus) : corpus_(corpus) {}
    bool done() const override { return index_ >= corpus_.size(); }
    void Next() override { if (!done()) ++index_; }
    const std::string& value() const override { return corpus_[index_]; }
    absl::Status status() const override { return absl::OkStatus(); }
private:
    const std::vector<std::string>& corpus_;
    std::size_t index_ = 0;
};

void writeFile(const std::string& path, const std::string& data) {
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out || !out.write(data.data(), static_cast<std::streamsize>(data.size()))) {
        throw std::runtime_error("unable to write " + path);
    }
}

bool beginsWithAsciiUppercase(const std::string& piece) {
    if (piece.size() == 1 && piece.front() >= 'A' && piece.front() <= 'Z') return true;
    // Byte-fallback pieces are serialized by SentencePiece as <0xNN>.
    return piece.size() == 6 && piece[0] == '<' && piece[1] == '0' && piece[2] == 'x' &&
           piece[5] == '>' &&
           ((piece[3] == '4' && piece[4] >= '1' && piece[4] <= '9') ||
            (piece[3] == '5' && piece[4] >= '0' && piece[4] <= 'A'));
}
} // namespace

int main(int argc, char** argv) {
    if (argc != 3) {
        std::cerr << "usage: GenerateSentencePieceModel MODEL_PATH IDS_HEADER_PATH\n";
        return 2;
    }
    try {
        std::vector<std::string> corpus;
        corpus.reserve(std::size(Felidae::kBuiltinTokens) + 8);
        for (const auto& token : Felidae::kBuiltinTokens) corpus.emplace_back(token.spelling);
        corpus.emplace_back("identifier unicode café lambda example value native module method declaration");
        CorpusIterator iterator(corpus);
        sentencepiece::TrainerComponents components;
        components.sentence_iterator = &iterator;
        auto* spec = components.mutable_trainer_spec();
        spec->set_model_type(sentencepiece::TrainerSpec::BPE);
        spec->set_vocab_size(512);
        spec->set_hard_vocab_limit(false);
        spec->set_character_coverage(1.0F);
        spec->set_shuffle_input_sentence(false);
        spec->set_num_threads(1);
        spec->set_unk_id(0);
        // Every valid UTF-8 source byte must have an integer representation.
        // Without byte fallback, unrelated user-defined identifiers can both
        // become <unk> and no integer parser can distinguish their sequences.
        spec->set_byte_fallback(true);
        spec->set_bos_id(-1);
        spec->set_eos_id(-1);
        spec->set_pad_id(-1);
        for (const auto& token : Felidae::kBuiltinTokens) {
            spec->add_user_defined_symbols(std::string(token.spelling));
        }
        auto* normalizer = components.mutable_normalizer_spec();
        normalizer->set_name("identity");
        normalizer->set_add_dummy_prefix(false);
        normalizer->set_remove_extra_whitespaces(false);
        normalizer->set_escape_whitespaces(true);

        sentencepiece::SetMinLogLevel(2);
        std::string serialized;
        const auto status = sentencepiece::SentencePieceTrainer::Train(components, &serialized);
        if (!status.ok()) throw std::runtime_error(status.ToString());
        sentencepiece::ModelProto model;
        if (!model.ParseFromString(serialized)) throw std::runtime_error("model serialization failed");

        std::string ids = "// Generated by tools/GenerateSentencePieceModel.cpp. Do not edit.\n#pragma once\n\n";
        ids += "#include <cstdint>\n\nnamespace Felidae {\n";
        ids += "inline constexpr int kFelidaeBuiltinSentencePieceIds[] = {\n";
        for (const auto& token : Felidae::kBuiltinTokens) {
            int id = -1;
            for (int index = 0; index < model.pieces_size(); ++index) {
                if (model.pieces(index).piece() == token.spelling) { id = index; break; }
            }
            if (id < 0) throw std::runtime_error("missing built-in " + std::string(token.spelling));
            // idName is source-safe even when a grammar symbol itself is a
            // line-comment escape such as a backslash.
            ids += "    " + std::to_string(id) + ", // " + std::string(token.idName) + "\n";
        }
        ids += "};\n\nnamespace TokenId {\nusing Id = std::int32_t;\n";
        ids += "constexpr Id UNKNOWN = 0;\n";
        for (const auto& token : Felidae::kBuiltinTokens) {
            int id = -1;
            for (int index = 0; index < model.pieces_size(); ++index) {
                if (model.pieces(index).piece() == token.spelling) { id = index; break; }
            }
            ids += "constexpr Id " + std::string(token.idName) + " = " + std::to_string(id) + ";\n";
        }
        ids += "} // namespace TokenId\n\ninline constexpr bool isCapitalizedIdentifierStartId(TokenId::Id id) {\n";
        ids += "    switch (id) {\n";
        for (int index = 0; index < model.pieces_size(); ++index) {
            if (beginsWithAsciiUppercase(model.pieces(index).piece())) {
                ids += "        case " + std::to_string(index) + ": return true;\n";
            }
        }
        ids += "        default: return false;\n    }\n}\n";
        ids += "} // namespace Felidae\n";
        writeFile(argv[1], serialized);
        writeFile(argv[2], ids);
    } catch (const std::exception& error) {
        std::cerr << "felidae SentencePiece model generation failed: " << error.what() << '\n';
        return 1;
    }
    return 0;
}
