import "html_components.fx".

DocsBasics() =>
    facts := RenderMiniCard(input: HtmlCardData(title: "Facts", text: "Facts describe what is true: a person, relationship, event, row, or nested data record.")),
    rules := RenderMiniCard(input: HtmlCardData(title: "Rules", text: "Rules derive new truth from existing facts and conditions.")),
    queries := RenderMiniCard(input: HtmlCardData(title: "Queries", text: "Queries usually live in main() or named methods, where results can be returned and checked.")),
    methods := RenderMiniCard(input: HtmlCardData(title: "Methods", text: "Methods are explicit transformations over provided data, not hidden database scans.")),
    operators := RenderMiniCard(input: HtmlCardData(title: "Operators", text: "Arithmetic uses +, -, *, / and grouping. Boolean checks use ==, !=, comparisons, comma for AND, and | for OR.")),
    structures := RenderMiniCard(input: HtmlCardData(title: "Structures", text: "Arrays use [..], tuples and nested objects use {key: value}, and facts can contain repeated fields.")),
    guidance := RenderGuidance(doText: "Model durable knowledge as facts with named fields, then write main() to collect, filter, aggregate, and return the answer as a tuple.", dontText: "Do not hide important application behavior only in command-line queries. CLI queries are useful for inspection, but they are not a substitute for repeatable program output.", recommendText: "Start every learning example with a tiny fact database, one method or rule, and a main() return value. That pattern makes examples easy to test, document, and serve."),
    arithmeticCode := "CartLine(item: \"book\", qty: 2, price: 15).\nCartLine(item: \"pen\", qty: 5, price: 2).\n\nLineTotal(line: any) =>\n    subtotal := line.qty * line.price,\n    discounted := subtotal - 1,\n    return (item: line.item, subtotal: subtotal, discounted: discounted).\n\nmain() =>\n    lines := lambda(CartLine, line => LineTotal(line: line)),\n    totals := lambda(lines, line => line.subtotal),\n    return (add: 2 + 3, multiply: 2 * 3, grouped: (2 + 3) * 4, precedence: 2 + 3 * 4, cartTotal: sum(totals), lines: lines).",
    arithmeticExample := RenderExampleBlock(title: "Arithmetic: totals and precedence", text: "Arithmetic expressions can be returned directly, assigned to locals, or used inside filters. Parentheses make the intent visible when precedence could surprise a reader.", code: arithmeticCode),
    logicCode := "Person(name: \"Ada\", role: \"Engineer\", active: \"true\", score: 91).\nPerson(name: \"Mina\", role: \"Designer\", active: \"true\", score: 72).\nPerson(name: \"Ravi\", role: \"Engineer\", active: \"false\", score: 65).\n\nEligible(person: any) =>\n    person.active == \"true\",\n    person.score >= 80,\n    return (name: person.name, eligible: \"true\")\nelse\n    return (name: person.name, eligible: \"false\").\n\nmain() =>\n    engineers := lambda(Person, p => p.role == \"Engineer\"),\n    checks := lambda(Person, p => Eligible(person: p)),\n    activeHigh := lambda(checks, row => row.eligible == \"true\"),\n    return (engineers: count(engineers), activeHigh: count(activeHigh), checks: checks).",
    logicExample := RenderExampleBlock(title: "Logic: filters and eligibility", text: "Logical checks are ordinary conditions. Use comma-separated conditions as AND, comparison operators for filtering, and fallback branches or | rules when there are alternatives.", code: logicCode),
    part1 := str.concat(left: facts, right: rules),
    part2 := str.concat(left: part1, right: queries),
    part3 := str.concat(left: part2, right: methods),
    part4 := str.concat(left: part3, right: operators),
    part5 := str.concat(left: part4, right: structures),
    cards := RenderGrid(content: part5),
    examples := str.concat(left: arithmeticExample, right: logicExample),
    content1 := str.concat(left: cards, right: guidance),
    content := str.concat(left: content1, right: examples),
    return (HtmlRichSectionData(id: "basics", title: "Logic Programming Basics", p: "Logic programming starts from declarations of truth. Instead of describing every step like an imperative program, you describe facts and rules, then ask questions. In Felidae, the most accountable way to ask those questions is to put them in main() and return the answer as data.", p2: "Facts form an in-memory database, command-line queries can inspect that database, and methods transform inputs with immutable bindings. Begin with facts and rules, then learn arithmetic, boolean checks, arrays, tuples, and nested objects as the everyday building blocks of methods.", content: content, code: "Parent(parent: \"Alice\", child: \"Bob\").\nParent(parent: \"Bob\", child: \"Chandra\").\n\nGrandparent(grandparent: gp, child: c) =>\n    Parent(parent: gp, child: p),\n    Parent(parent: p, child: c).\n\nArithmeticResult() =>\n    return (add: 2 + 3, grouped: (2 + 3) * 4, precedence: 2 + 3 * 4).\n\nmain() =>\n    rows := lambda(Grandparent, row => row),\n    return (grandparents: rows, total: count(rows), arithmetic: ArithmeticResult()).", note: "See examples/arithmetic_and_boolean.fx for arithmetic, nil checks, and boolean return values. See examples/structures.fx for arrays, tuples, nested objects, and member access.", code2: "# Optional terminal inspection:\n# ./build/felidae family.fx '? Grandparent(grandparent: GP, child: Child)'\n\nPerson(name: \"Alice\", role: \"Engineer\", manager: \"Bob\").\nPerson(name: \"Carol\", role: \"Engineer\", manager: nil).\n\nmain() =>\n    engineers := lambda(Person, p => p.role == \"Engineer\"),\n    managed := lambda(engineers, p => p.manager != nil),\n    return (engineers: count(engineers), managed: count(managed), hasManagedEngineers: count(managed) > 0).")).
