import "html_components.fx".

DocsDataStructuresAlgorithms() =>
    arrays := RenderMiniCard(input: HtmlCardData(title: "Arrays", text: "Use [..] for ordered values. Read values with array.get and derive filtered arrays with lambda.")),
    tuples := RenderMiniCard(input: HtmlCardData(title: "Tuples", text: "Use {key: value} for named records returned from methods or nested inside facts.")),
    objects := RenderMiniCard(input: HtmlCardData(title: "Nested Objects", text: "Member access chains such as order.item.sku and object.z.w keep data readable without SQL.")),
    algorithms := RenderMiniCard(input: HtmlCardData(title: "Algorithms", text: "Write small named methods over current primitives: lambda, count, sort, array.get, array.len, array.push, and fallback recursion.")),
    scenarioCode := "Product(id: \"p1\", name: \"Notebook\", price: 8, stock: 20).\nProduct(id: \"p2\", name: \"Pen\", price: 2, stock: 0).\nProduct(id: \"p3\", name: \"Bag\", price: 35, stock: 4).\n\nAvailableProduct(row: any) =>\n    where row.stock > 0,\n    return (name: row.name, value: row.price * row.stock).\n\nmain() =>\n    available := lambda(Product, row => AvailableProduct(row: row)),\n    values := lambda(available, row => row.value),\n    names := sort(lambda(available, row => row.name)),\n    return (available: count(available), names: names, inventoryValue: sum(values)).",
    scenarioPanel := RenderExampleBlock(title: "Product facts to inventory summary", text: "Use facts when the dataset has named records, arrays when order matters, and methods when the algorithm should be reusable. This example keeps the dataset, transformation, aggregate, and returned tuple in one readable block.", code: scenarioCode),
    part1 := str.concat(left: arrays, right: tuples),
    part2 := str.concat(left: part1, right: objects),
    part3 := str.concat(left: part2, right: algorithms),
    cards := RenderGrid(content: part3),
    content := str.concat(left: cards, right: scenarioPanel),
    return (HtmlRichSectionData(id: "data-structures", title: "Data Structures And Algorithms", p: "Felidae data structures are intentionally close to fact syntax. Arrays model ordered collections, tuples model named records, nested objects model grouped properties, and facts can contain repeated fields that behave like arrays inside methods.", p2: "Keep algorithm examples small and explicit. Use the current array contract for reliable examples: read with array.get, measure with array.len, append with array.push, filter with lambda, and sort with the built-in aggregate. Use method fallback branches for recursive scalar algorithms such as factorial.", content: content, code: "Numbers := [1, 3, 5, 7, 9].\n\nLinearSearch(data: array, target: number) =>\n    matches := lambda(data, value => value == target),\n    return (target: target, found: count(matches) > 0, matches: matches).\n\nmain() =>\n    second := array.get(data: Numbers, position: 1),\n    length := array.len(data: Numbers),\n    result := LinearSearch(data: Numbers, target: 7),\n    return (second: second, length: length, search: result).", note: "Related examples in the repository: examples/structures.fx shows arrays, tuples, nested objects, and member access; examples/arithmetic_and_boolean.fx shows arithmetic and boolean checks; examples/operators.fx shows OR branches; examples/factorial.fx shows fallback recursion.", code2: "SortedSearch(data: array, target: number) =>\n    sorted := sort(data),\n    matches := lambda(sorted, value => value == target),\n    return (target: target, sorted: sorted, found: count(matches) > 0).\n\nFactorial(n: int) =>\n    n == 0,\n    return 1\nelse\n    return n * Factorial(n: n - 1).\n\nmain() =>\n    return (\n        linear: LinearSearch(data: [4, 8, 15, 16], target: 15),\n        sortedSearch: SortedSearch(data: [9, 1, 7, 3], target: 7),\n        factorial: Factorial(n: 5)\n    ).")).
