import ("json", "str").

DocSearchEntry(id: "overview", title: "Overview", route: "#overview", tags: "felidae logic programming facts data code database overview", summary: "Felidae is a functional logic language where facts are executable knowledge and documentation is generated from data.", searchText: "overview felidae logic programming facts data code database executable knowledge generated documentation").
DocSearchEntry(id: "basics", title: "Logic Programming Basics", route: "#basics", tags: "logic programming facts rules queries basics arithmetic boolean", summary: "Start with facts, rules, arithmetic, boolean checks, arrays, and main() return values.", searchText: "basics logic programming facts rules queries relationships dataflow arithmetic boolean operators arrays tuples main examples").
DocSearchEntry(id: "start", title: "Getting Started", route: "#start", tags: "install run command celidae felidae main query", summary: "Run Felidae programs through main(), use optional CLI fact inspection, and use Celidae for checks, graphs, and editor diagnostics.", searchText: "getting started run command main query cli celidae felidae check graph diagnostics").
DocSearchEntry(id: "syntax", title: "Syntax Essentials", route: "#syntax", tags: "syntax named arguments immutable fields str concat", summary: "Felidae uses named fields, immutable := bindings, package calls, member access, and strict current syntax.", searchText: "syntax named fields named arguments immutable bindings str concat left right package calls member access").
DocSearchEntry(id: "facts", title: "Facts As Database", route: "#facts", tags: "facts database no sql db repeated fields nested data", summary: "Facts are the database layer. Repeated fields become arrays and can be queried with db helpers or lambdas.", searchText: "facts database no sql db repeated fields arrays nested rain cat data").
DocSearchEntry(id: "queries", title: "Queries And Aggregates", route: "#queries", tags: "queries aggregates search contains count db main cli", summary: "Prefer reusable queries in main() or methods, with command-line queries reserved for ad hoc fact inspection.", searchText: "queries aggregates main methods search contains count average sum min max db all find first command line").
DocSearchEntry(id: "methods", title: "Rules, Methods, And Returns", route: "#methods", tags: "rules methods returns arguments fallback where tuple main", summary: "Use rules for relationships and methods/main() for repeatable application queries and structured return values.", searchText: "rules methods returns explicit inputs where fallback tuple immutable arguments main queries").
DocSearchEntry(id: "data-structures", title: "Data Structures And Algorithms", route: "#data-structures", tags: "arrays tuples nested objects algorithms linear search binary search quick sort", summary: "Arrays, tuples, nested objects, member access, and beginner algorithm examples such as search and sort.", searchText: "data structures algorithms arrays tuples nested objects member access linear search binary search quick sort arithmetic boolean examples structures").
DocSearchEntry(id: "testing", title: "Testing Felidae Programs", route: "#testing", tags: "testing unit tests smoke tests best practices celidae check json", summary: "How to write Felidae unit-style checks, smoke tests, negative tests, and CI diagnostics.", searchText: "testing unit tests smoke process exec assert contains best practices main celidae check json examples felidae test suite").
DocSearchEntry(id: "reference", title: "Language Reference", route: "#reference", tags: "reference docs language operators visualization exceptions", summary: "Exact language rules for operators, anonymous variables, runtime behavior, exceptions, and visualization.", searchText: "language reference operators anonymous variables exceptions visualization runtime celidae").
DocSearchEntry(id: "stdlib", title: "Standard Library", route: "#stdlib", tags: "stdlib modules file http json csv str array math db probability", summary: "Core modules provide file, HTTP, JSON, CSV, strings, arrays, math, facts, probability, ML, process, and thread helpers.", searchText: "standard library stdlib modules file http json csv str array math db probability ml process thread").
DocSearchEntry(id: "libraries", title: "Core Modules And Libraries", route: "#libraries", tags: "core modules libraries native imports", summary: "A module index for Felidae declaration files and native-backed library capabilities.", searchText: "core modules libraries native imports db probability str http json csv").
DocSearchEntry(id: "lib-db", title: "Library: db", route: "#lib-db", tags: "db fact database no sql query", summary: "No-SQL access to loaded facts with db.all, db.find, db.first, db.count, db.types, and db.fields.", searchText: "library db facts database no sql all find first count types fields main methods").
DocSearchEntry(id: "lib-str", title: "Library: str", route: "#lib-str", tags: "str string join concat split text", summary: "Text projection, matching, cleanup, splitting, joining, and replacement.", searchText: "library str string concat join lower upper trim split replace contains startsWith endsWith text projection").
DocSearchEntry(id: "lib-array", title: "Library: array", route: "#lib-array", tags: "array list get len push", summary: "Ordered value helpers for reading, measuring, and appending arrays.", searchText: "library array get len push ordered values list").
DocSearchEntry(id: "lib-json", title: "Library: json", route: "#lib-json", tags: "json parse get has keys set remove toText", summary: "JSON boundary values for external systems and structured browser data.", searchText: "library json parse get has keys set remove toText serialize boundary data").
DocSearchEntry(id: "lib-csv", title: "Library: csv", route: "#lib-csv", tags: "csv rows table facts import export", summary: "CSV parsing, row updates, exports, and fact generation.", searchText: "library csv parse rows addRow findRows updateRows deleteRows toFacts toFelidaeFacts table import export").
DocSearchEntry(id: "lib-file", title: "Library: file", route: "#lib-file", tags: "file read write append exists delete", summary: "Local file reads, writes, appends, existence checks, and deletes.", searchText: "library file readFile readLines writeFile writeLines appendFile exists deleteFile local io").
DocSearchEntry(id: "lib-http", title: "Library: http", route: "#lib-http", tags: "http server hosting request response", summary: "HTTP client calls, response helpers, and static documentation serving.", searchText: "library http get post put delete serveStatic HttpResponse HttpHtmlResponse HttpServeResponse server hosting").
DocSearchEntry(id: "lib-math", title: "Library: math", route: "#lib-math", tags: "math numeric scalar trigonometry", summary: "Scalar constants, numeric helpers, and trigonometry.", searchText: "library math pi e random pow sqrt sin cos tan log exp abs floor ceil round numeric scalar").
DocSearchEntry(id: "lib-ml", title: "Library: ml", route: "#lib-ml", tags: "ml fact mining clustering regression associations prediction", summary: "Fact profiling, clustering, association discovery, classification, regression, and generated .fx models.", searchText: "library ml machine learning fact mining k means clustering profile_facts correlate_facts discover_associations train_decision_tree train_linear_regression predict_fact predict_numeric_fact model_fx").
DocSearchEntry(id: "lib-system", title: "Library: system", route: "#lib-system", tags: "system print type runtime", summary: "Runtime print and type inspection helpers.", searchText: "library system print type instanceof runtime output").
DocSearchEntry(id: "lib-console", title: "Library: console", route: "#lib-console", tags: "console terminal interactive", summary: "Interactive terminal input and output.", searchText: "library console readLine write writeLine terminal interactive").
DocSearchEntry(id: "lib-process", title: "Library: process", route: "#lib-process", tags: "process platform exec sleep host", summary: "Platform detection, host command execution, and sleep.", searchText: "library process platform exec sleep host command operational").
DocSearchEntry(id: "lib-thread", title: "Library: thread", route: "#lib-thread", tags: "thread create start pause stop status result", summary: "Thread handles for independent method execution.", searchText: "library thread createThread start pause stop status result worker handle").
DocSearchEntry(id: "probability", title: "Probability On Facts", route: "#probability", tags: "probability statistics normalize entropy variance correlation facts", summary: "Probability helpers operate on arrays derived from facts for distributions, similarity, and statistical analysis.", searchText: "probability statistics normalize entropy variance standard deviation covariance correlation facts rain cats similarity").
DocSearchEntry(id: "native", title: "Native Modules", route: "#native", tags: "native modules c++ bridge performance", summary: "Native modules keep heavy work behind stable Felidae declarations while C++ handles implementation details.", searchText: "native modules bridge cpp performance runtime implementation").
DocSearchEntry(id: "debugging", title: "Debugging And Editor Diagnostics", route: "#debugging", tags: "debugging diagnostics celidae vscode lsp graph", summary: "Celidae owns diagnostics, graph inspection, visualization, LSP, and editor integration workflows.", searchText: "debugging diagnostics celidae vscode intellij lsp graph visualization check json").
DocSearchEntry(id: "hosting", title: "Documentation Hosting", route: "#hosting", tags: "hosting documentation server html components", summary: "The docs site is a Felidae program that renders documentation facts into HTML at startup.", searchText: "hosting documentation server html components render startup generated static").
DocSearchEntry(id: "server", title: "Server Features", route: "#server", tags: "server routes navigation spa copy playground search", summary: "The server renders a single-page app with routing, navigation, code copy, playground, and generated docs.", searchText: "server features routes navigation spa copy playground search static response").
DocSearchEntry(id: "download", title: "Download Felidae", route: "#download", tags: "download felidae celidae extension interpreter binaries releases wasm browser", summary: "Separate product download page for Felidae, Celidae, editor extensions, source packages, and WASM assets.", searchText: "download felidae celidae extension interpreter vscode intellij build install windows linux macos binaries releases wasm browser playground").
DocSearchEntry(id: "version", title: "Version And Release Notes", route: "#version", tags: "version release notes snapshot", summary: "Current documentation snapshot and product split between Felidae execution and Celidae diagnostics.", searchText: "version release notes snapshot felidae celidae diagnostics execution").
DocSearchEntry(id: "milestones", title: "Language Milestones", route: "#milestones", tags: "milestones roadmap interpreter visualizer extension celidae vscode intellij", summary: "Development milestones from interpreter to fact database, visualizer, editor extensions, documentation SPA, and future releases.", searchText: "milestones roadmap interpreter facts database stdlib visualizer celidae diagnostics vscode intellij extension documentation spa releases").
DocSearchEntry(id: "about", title: "About Felidae", route: "#about", tags: "about github project code data", summary: "Project information, design principles, repository link, and editor ecosystem notes.", searchText: "about github project repository code data logic language").
DocSearchEntry(id: "playground", title: "Playground", route: "#playground", tags: "playground examples copy run command wasm browser interpreter", summary: "Edit a Felidae sample, run it through the WASM interpreter, or copy the native command.", searchText: "playground examples copy run command local sample editor wasm browser interpreter").

DocsSearchIndex() =>
    return (lambda(DocSearchEntry, entry => entry)).

DocsSearchJson() =>
    rows := DocsSearchIndex(),
    return (json.toText(data: rows)).

SearchDocumentationResult(entry: any, query: string) =>
    matched := str.contains(data: entry.searchText, needle: query),
    matched == "true",
    return (
        id: entry.id,
        title: entry.title,
        route: entry.route,
        summary: entry.summary
    ).

SearchDocumentation(query: string) =>
    normalized := str.lower(data: query),
    matches := lambda(DocSearchEntry, entry => SearchDocumentationResult(entry: entry, query: normalized)),
    return (
        query: query,
        count: count(matches),
        results: matches
    ).

