import ("html_components.fx", "str").

DocsLibraryStr() =>
    cards := RenderModuleGrid(content: str.join(data: [
        RenderMiniCard(input: HtmlCardData(title: "Projection", text: "concat joins two strings; join renders arrays with a delimiter.")),
        RenderMiniCard(input: HtmlCardData(title: "Search", text: "contains, startsWith, and endsWith return string-shaped truth values.")),
        RenderMiniCard(input: HtmlCardData(title: "Cleanup", text: "lower, upper, trim, split, and replace prepare text before matching or rendering."))
    ], delimiter: "")),
    return (HtmlRichSectionData(id: "lib-str", title: "Library: str", p: "The str module handles small text operations used in projections, labels, generated documentation, command output checks, and search preparation.", p2: "Use str.concat(left: ..., right: ...) for two strings and str.join(data: ..., delimiter: ...) for arrays. Keeping those roles separate prevents long concat ladders in documentation and server code.", content: cards, code: "import \"str\".\n\nmain() =>\n    first := str.concat(left: \"Felidae\", right: \" docs\"),\n    tags := str.join(data: [\"facts\", \"logic\", \"docs\"], delimiter: \", \"),\n    normalized := str.lower(data: \"Search Term\"),\n    return (title: first, tags: tags, normalized: normalized).", note: "Use str.join when rendering repeated fragments. Use str.concat only when there are exactly two string parts.", code2: "str.contains(data: \"facts as data\", needle: \"facts\")\nstr.trim(data: \"  Felidae  \")\nstr.replace(data: \"a-b-c\", search: \"-\", replacement: \":\")")).

DocsLibraryArray() =>
    cards := RenderModuleGrid(content: str.join(data: [
        RenderMiniCard(input: HtmlCardData(title: "Read", text: "array.get reads a value by position.")),
        RenderMiniCard(input: HtmlCardData(title: "Measure", text: "array.len returns the number of values.")),
        RenderMiniCard(input: HtmlCardData(title: "Build", text: "array.push returns a new array with one added value."))
    ], delimiter: "")),
    return (HtmlRichSectionData(id: "lib-array", title: "Library: array", p: "The array module is intentionally small. Arrays are ordered values, while facts remain the preferred shape for durable named knowledge.", p2: "Use array helpers when order matters or when a native module returns a list. For filtering and projection, prefer lambda(data, row => ...) so the transformation stays visible.", content: cards, code: "import \"array\".\n\nmain() =>\n    names := [\"Ada\", \"Mina\", \"Ravi\"],\n    first := array.get(data: names, position: 0),\n    total := array.len(data: names),\n    extended := array.push(data: names, value: \"Nia\"),\n    return (first: first, total: total, extended: extended).", note: "Use facts when fields need names. Use arrays when order is the important part of the data.", code2: "scores := [91, 72, 65]\npassing := lambda(scores, value => value >= 70)\ncount(passing)")).

DocsLibraryDb() =>
    guidance := RenderGuidance(doText: "Keep fact queries inside main() or named methods, and return named tuples so the result is testable and documentable.", dontText: "Do not use db helpers as hidden global state inside unrelated helpers. Pass data into methods when the method should be reusable.", recommendText: "Use db.first for one expected record, db.find for filtered rows, and db.all when the fact type is the dataset."),
    return (HtmlRichSectionData(id: "lib-db", title: "Library: db", p: "The db module treats loaded facts as the database. It is the no-SQL query surface for facts already loaded into the interpreter: direct facts, imported facts, and facts created through ordinary Felidae source.", p2: "db helpers are explicit. A method does not silently scan every fact; use db.all, db.find, db.first, db.count, db.types, or db.fields when fact database access is intended.", content: guidance, code: "import \"db\".\n\nCustomer(name: \"Ada\", city: \"SEA\", status: \"active\").\nCustomer(name: \"Mina\", city: \"BLR\", status: \"active\").\n\nmain() =>\n    rows := db.find(type: \"Customer\", field: \"status\", equals: \"active\"),\n    names := lambda(rows, row => row.name),\n    return (count: count(rows), names: names).", note: "db is critical because it defines the fact database contract. Keep field names stable and clear.", code2: "db.all(type: \"Customer\")\ndb.first(type: \"Customer\", field: \"name\", equals: \"Ada\")\ndb.count(type: \"Customer\")\ndb.fields(type: \"Customer\")")).

DocsLibraryJson() =>
    cards := RenderModuleGrid(content: str.join(data: [
        RenderMiniCard(input: HtmlCardData(title: "Read", text: "parse turns JSON text into a runtime value; get reads a key.")),
        RenderMiniCard(input: HtmlCardData(title: "Inspect", text: "has and keys let code check shape before accessing fields.")),
        RenderMiniCard(input: HtmlCardData(title: "Write", text: "set, remove, and toText create JSON-shaped outputs."))
    ], delimiter: "")),
    return (HtmlRichSectionData(id: "lib-json", title: "Library: json", p: "The json module is for exchanging runtime values with external systems. It is useful for API responses, saved reports, imported payloads, and browser-facing data.", p2: "Keep durable application knowledge as Felidae facts. Convert to JSON at the boundary when another system needs JSON text or when a documentation page needs embedded structured data.", content: cards, code: "import \"json\".\n\nmain() =>\n    payload := json.parse(data: \"{\\\"name\\\":\\\"Ada\\\",\\\"role\\\":\\\"Engineer\\\"}\"),\n    name := json.get(data: payload, key: \"name\"),\n    hasRole := json.has(data: payload, key: \"role\"),\n    keys := json.keys(data: payload),\n    return (name: name, hasRole: hasRole, keys: keys).", note: "JSON is a boundary format, not the fact database. Store durable knowledge as facts and serialize only when exchanging data.", code2: "updated := json.set(data: payload, key: \"active\", value: \"true\")\nwithoutRole := json.remove(data: updated, key: \"role\")\ntext := json.toText(data: withoutRole)")).

DocsLibraryCsv() =>
    cards := RenderModuleGrid(content: str.join(data: [
        RenderMiniCard(input: HtmlCardData(title: "Parse", text: "csv.parse turns CSV text into rows.")),
        RenderMiniCard(input: HtmlCardData(title: "Rows", text: "addRow, findRows, updateRows, and deleteRows work on row arrays.")),
        RenderMiniCard(input: HtmlCardData(title: "Facts", text: "toFacts and toFelidaeFacts convert table-shaped rows into fact-shaped data."))
    ], delimiter: "")),
    return (HtmlRichSectionData(id: "lib-csv", title: "Library: csv", p: "The csv module is for table-shaped text at system boundaries. Use it when importing spreadsheets, exporting reports, or generating Felidae facts from rows.", p2: "CSV has columns and rows, but it does not carry nested structure as clearly as Felidae facts. Convert CSV into facts when the data becomes part of the program's durable knowledge.", content: cards, code: "import \"csv\".\n\nmain() =>\n    rows := csv.parse(data: \"name,role\\nAda,Engineer\\nMina,Designer\"),\n    engineers := csv.findRows(data: rows, key: \"role\", value: \"Engineer\"),\n    withRow := csv.addRow(data: rows, row: {name: \"Ravi\", role: \"Engineer\"}),\n    return (engineers: engineers, total: count(withRow)).", note: "CSV is best at import and export. Once rows become application knowledge, convert them into named Felidae facts.", code2: "factsText := csv.toFelidaeFacts(data: rows, type: \"Employee\")\nupdated := csv.updateRows(data: rows, key: \"name\", value: \"Ada\", patch: {role: \"Lead\"})\nremaining := csv.deleteRows(data: rows, key: \"role\", value: \"Designer\")")).

DocsLibraryFile() =>
    guidance := RenderGuidance(doText: "Keep file paths explicit in main() or edge methods, and convert file content into facts or tuples before deeper processing.", dontText: "Do not hide writes or deletes inside general-purpose helpers. File operations change the host environment and should be visible.", recommendText: "Use readLines for large line-oriented inputs and writeFile/writeLines only when the output path is intentional."),
    return (HtmlRichSectionData(id: "lib-file", title: "Library: file", p: "The file module provides native-backed local file I/O: read whole files, read lines, write text, append text, check existence, and delete files.", p2: "Use file at the boundary of a program. After reading a file, shape the data into facts, arrays, or tuples so the rest of the program remains testable.", content: guidance, code: "import \"file\".\n\nmain() =>\n    exists := file.exists(path: \"data/input.fx\"),\n    text := file.readFile(path: \"data/input.fx\"),\n    lines := file.readLines(path: \"data/input.fx\"),\n    return (exists: exists, characters: length(text), lines: count(lines)).", note: "File writes and deletes are host-side effects. Keep the path and mode close to the main workflow.", code2: "file.writeFile(path: \"out/report.fx\", data: \"Report(status: \\\"ok\\\").\", mode: \"write\")\nfile.appendFile(path: \"out/report.fx\", data: \"\\nReport(status: \\\"done\\\").\")\nfile.deleteFile(path: \"out/old-report.fx\")")).

DocsLibraryHttp() =>
    guidance := RenderGuidance(doText: "Keep hosts, ports, content types, and response bodies explicit.", dontText: "Do not mix server hosting examples with unrelated file or process code on the same page.", recommendText: "Use Http* helper methods for readable response records, then pass those records to HttpServeResponse."),
    return (HtmlRichSectionData(id: "lib-http", title: "Library: http", p: "The http module provides native-backed client calls and simple static response serving. It is used by the documentation server to serve the generated SPA from Felidae code.", p2: "The raw http.* functions are native calls. The HttpResponse, HttpHtmlResponse, HttpJsonResponse, HttpUrl, and HttpServeResponse helpers keep application code data-shaped.", content: guidance, code: "import \"http\".\n\nmain() =>\n    page := HttpHtmlDocument(title: \"Felidae\", body: \"<h1>ok</h1>\"),\n    response := HttpHtmlResponse(body: page),\n    return (response: response).", note: "For production documentation hosting, run Felidae behind Nginx and keep the native server bound to 127.0.0.1.", code2: "HttpServeResponse(host: \"127.0.0.1\", port: 8090, response: response)\nHttpJsonResponse(body: \"{\\\"ok\\\":true}\")\nhttp.get(url: \"https://example.com\")")).

DocsLibraryMath() =>
    cards := RenderModuleGrid(content: str.join(data: [
        RenderMiniCard(input: HtmlCardData(title: "Constants", text: "pi and e provide numeric constants.")),
        RenderMiniCard(input: HtmlCardData(title: "Numeric", text: "abs, floor, ceil, round, sqrt, pow, log, log10, exp.")),
        RenderMiniCard(input: HtmlCardData(title: "Trigonometry", text: "sin, cos, tan, asin, acos, atan, atan2."))
    ], delimiter: "")),
    return (HtmlRichSectionData(id: "lib-math", title: "Library: math", p: "The math module contains scalar numeric helpers. Use it for deterministic calculations around values already derived from facts or arrays.", p2: "Keep numeric inputs visible near the call. If the values come from facts, derive the numeric array first, then call math functions in a named method or main().", content: cards, code: "import \"math\".\n\nmain() =>\n    root := math.sqrt(value: 16),\n    distance := math.abs(value: -12),\n    power := math.pow(base: 2, exponent: 5),\n    rounded := math.round(value: 3.6),\n    return (root: root, distance: distance, power: power, rounded: rounded).", note: "math works on scalar numbers. Use probability for distributions and ml for vector scoring.", code2: "angle := math.atan2(y: 1, x: 1)\nwave := math.sin(value: angle)\nrandom := math.random(min: 1, max: 10)")).

DocsLibraryMl() =>
    cards := RenderModuleGrid(content: str.join(data: [
        RenderMiniCard(input: HtmlCardData(title: "Activation", text: "sigmoid and relu transform one numeric value.")),
        RenderMiniCard(input: HtmlCardData(title: "Vectors", text: "dot compares two vectors by multiplication and sum.")),
        RenderMiniCard(input: HtmlCardData(title: "Fact Mining", text: "profile_facts, cluster_facts, and discover_associations analyze key-value facts.")),
        RenderMiniCard(input: HtmlCardData(title: "Models", text: "train_decision_tree and train_linear_regression return inspectable Felidae model facts."))
    ], delimiter: "")),
    return (HtmlRichSectionData(id: "lib-ml", title: "Library: ml", p: "The ml module treats Felidae facts as an analyzable fact database. Use it for lightweight data mining: numeric profiling, k-means clustering, key-value association discovery, classification, and numeric prediction.", p2: "Models are returned as structured values with model_fx source text, so trained output can be saved as a .fx file and inspected like ordinary Felidae code/data.", content: cards, code: "import \"ml\".\n\nmain() =>\n    customers := [\n        {age: 24, spend: 120, visits: 3, segment: \"starter\", region: \"south\"},\n        {age: 45, spend: 820, visits: 13, segment: \"premium\", region: \"west\"}\n    ],\n    profile := ml.profile_facts(facts: customers, features: [\"age\", \"spend\", \"visits\"]),\n    clusters := ml.cluster_facts(facts: customers, features: [\"age\", \"spend\", \"visits\"], clusters: 2),\n    model := ml.train_decision_tree(facts: customers, target: \"segment\", features: [\"age\", \"spend\", \"visits\"]),\n    prediction := ml.predict(model: model, input: {age: 42, spend: 780, visits: 12}),\n    return (profile: profile, clusters: clusters, prediction: prediction).", note: "Keep source facts visible near the model call. Use ml.save_model only when writing an explicit generated .fx model artifact is part of the workflow.", code2: "ml.correlate_facts(facts: rows, left: \"visits\", right: \"spend\")\nml.train_linear_regression(facts: rows, target: \"revenue\", feature: \"visitors\")\nml.predict_numeric_fact(facts: rows, input: {visitors: 220}, target: \"revenue\", feature: \"visitors\")")).

DocsLibrarySystem() =>
    return (HtmlRichSectionData(id: "lib-system", title: "Library: system", p: "The system module provides low-level runtime inspection and development output helpers.", p2: "Prefer returning structured data from main() for stable program behavior. Use system.print for startup messages, service logs, or temporary development feedback.", content: "", code: "import \"system\".\n\nmain() =>\n    system.print(value: \"checking docs\"),\n    return (status: \"printed\").", note: "Printed output is useful for humans, but returned tuples are easier for docs, tests, and automation to verify.", code2: "type(value: [1, 2, 3], name: kind)\ninstanceof(value: 42, type: \"number\")")).

DocsLibraryConsole() =>
    return (HtmlRichSectionData(id: "lib-console", title: "Library: console", p: "The console module provides interactive terminal input and output helpers.", p2: "Use console helpers for interactive scripts. Documentation and automated examples should usually return data from main() instead of requiring user input.", content: "", code: "import \"console\".\n\nTenCheck(x: number) =>\n    x == 10,\n    return (matched: true, message: \"x is ten\")\nelse\n    return (matched: false, message: \"x is not ten\").\n\nmain() =>\n    x := console.inputNumber(print: \"enter x: \"),\n    return (x: x, check: TenCheck(x: x)).", note: "console.input returns text. Use console.inputNumber when the next condition should compare against a number such as x == 10.", code2: "name := console.input(print: \"enter name: \")\nconsole.write(value: \"Hello, \")\nconsole.writeLine(value: name)\nraw := console.readLine()")).

DocsLibraryProcess() =>
    guidance := RenderGuidance(doText: "Use process.platform for OS-aware tooling and keep process.exec commands explicit.", dontText: "Do not use process.exec for ordinary logic examples, docs rendering, or hidden application behavior.", recommendText: "When a command must run, return the command and output together so tests can audit it."),
    return (HtmlRichSectionData(id: "lib-process", title: "Library: process", p: "The process module exposes host process helpers: platform detection, command execution, and sleep.", p2: "This module is operational and can affect the host environment. Use it for tooling, smoke tests, packaging scripts, or controlled integration points, not for core logic programming examples.", content: guidance, code: "import \"process\".\n\nmain() =>\n    platform := process.platform(),\n    waited := process.sleep(milliseconds: 10),\n    return (platform: platform, waited: waited).", note: "process.exec runs host commands. Treat command strings as operational boundaries and keep them visible.", code2: "output := process.exec(command: \"build\\\\felidae_debug.exe docs\\\\server.fx --check-json\")\nreturn (command: \"docs check\", output: output)")).

DocsLibraryThread() =>
    guidance := RenderGuidance(doText: "Use threads for isolated long-running method work where a handle, status, and result make sense.", dontText: "Do not introduce threads into beginner examples or simple fact queries. They add coordination cost.", recommendText: "Create, start, check status, then read result through the thread handle."),
    return (HtmlRichSectionData(id: "lib-thread", title: "Library: thread", p: "The thread module runs a method on an independent interpreter snapshot and returns a handle that can be started, paused, stopped, queried, and joined through result access.", p2: "Thread usage is advanced. Keep the threaded function name explicit and return status/result data so the workflow remains observable.", content: guidance, code: "import \"thread\".\n\nWorker() =>\n    return (status: \"done\").\n\nmain() =>\n    worker := thread.createThread(function: \"Worker\"),\n    started := thread.start(thread: worker),\n    status := thread.status(thread: worker),\n    result := thread.result(thread: worker),\n    return (started: started, status: status, result: result).", note: "Threads should not hide fact database mutations. Prefer pure method work or clearly documented operational tasks.", code2: "thread.pause(thread: worker)\nthread.stop(thread: worker)")).
