import "html_components.fx".

DocsSyntax() =>
    guidance := RenderGuidance(doText: "Use key : value inside facts and method calls, use := for local immutable bindings, and use str.concat(left: ..., right: ...) for string joins.", dontText: "Do not use ::, positional guessing, or str.concat(data: ...). Those forms drift away from current Felidae syntax and make docs misleading.", recommendText: "When an example mixes facts, arrays, modules, and return values, keep every argument named. Readers should understand the data shape without reading implementation code."),
    callsCode := "import \"str\".\n\nGreeting(name: string) =>\n    left := str.concat(left: \"Hello, \", right: name),\n    return (str.concat(left: left, right: \"!\" )).\n\nmain() =>\n    message := Greeting(name: \"Ada\"),\n    return (message: message).",
    callsPanel := RenderExampleBlock(title: "Named calls and local bindings", text: "The most common mistakes are using the wrong argument name or hiding values behind positional calls. Keep every call readable with named arguments.", code: callsCode),
    comparisonsCode := "Score(name: \"Ada\", value: 91).\nScore(name: \"Mina\", value: 72).\nScore(name: \"Ravi\", value: 65).\n\nGrade(row: any) =>\n    where row.value >= 90,\n    return (name: row.name, grade: \"A\")\nelse\n    where row.value >= 70,\n    return (name: row.name, grade: \"B\")\nelse\n    return (name: row.name, grade: \"C\").\n\nmain() =>\n    passing := lambda(Score, row => row.value >= 70),\n    grades := lambda(Score, row => Grade(row: row)),\n    return (passing: count(passing), grades: grades).",
    comparisonsPanel := RenderExampleBlock(title: "Comparisons and fallback branches", text: "Comparisons can be used in where clauses, lambdas, and rule bodies. Return the boolean-shaped result so users can see exactly what matched.", code: comparisonsCode),
    panels := str.concat(left: callsPanel, right: comparisonsPanel),
    content := str.concat(left: guidance, right: panels),
    return (HtmlRichSectionData(id: "syntax", title: "Syntax Essentials", p: "Felidae uses explicit named fields so data remains readable as both code and database rows. Bind locals with immutable :=, call modules with ., pass named arguments with :, terminate declarations with ., and prefer named arguments over positional guessing.", p2: "Use . for package calls and field access, for example array.get(...) and person.name. Use : for named arguments and local namespaces. :: is not part of current Felidae syntax. For string concatenation, use str.concat(left: value, right: suffix); both sides should be strings, so convert structured or numeric values first when needed.", content: content, code: "import (\"db\", \"json\", \"probability\", \"str\").\nPerson(name: \"Ravi\", age: 30, role: \"Engineer\").\n\nmain() =>\n    ages := lambda(Person, p => p.age),\n    average := probability.mean(data: ages),\n    averageText := json.toText(data: average),\n    label := str.concat(left: \"Average age: \", right: averageText),\n    return (averageAge: average, label: label).", note: "Strict named fields are the bridge between logic syntax and fact-database readability. If the reader cannot tell what a value means from the field name, the fact probably needs a clearer shape.", code2: "Person(name: \"Alice\").\nvalue := array.get(data: [1, 2, 3], position: 0).\nx == person.name.\ntext := str.concat(left: \"hello\", right: \" world\").")).
