import "html_components.fx".

DocsTesting() =>
    smoke := RenderMiniCard(input: HtmlCardData(title: "Smoke Tests", text: "A smoke test runs a complete .fx file and checks a few stable substrings in the returned tuple. Use this for examples, docs snippets, and regression bugs.")),
    unit := RenderMiniCard(input: HtmlCardData(title: "Unit-Style Methods", text: "Keep pure transformations in named methods, then call them from main() with small input facts. Return expected and actual values so failures are obvious.")),
    negative := RenderMiniCard(input: HtmlCardData(title: "Negative Cases", text: "Keep invalid syntax, type mismatches, and bad imports under examples/invalid or tests/invalid. Assert parser and AST diagnostics with felidae_debug.")),
    ci := RenderMiniCard(input: HtmlCardData(title: "CI Checks", text: "Run felidae_debug --check-json for diagnostics, then run Felidae programs that assert behavior. Use main() results as the stable contract.")),
    part1 := str.concat(left: smoke, right: unit),
    part2 := str.concat(left: part1, right: negative),
    cards := RenderGrid(content: str.concat(left: part2, right: ci)),
    guidance := RenderGuidance(doText: "Test through main(), named methods, and stable returned tuples. Keep the expected value near the input data so a failed test reads like a small story.", dontText: "Do not rely only on one-off command-line queries for regression coverage. CLI queries are useful while debugging, but tests should be repeatable from a file.", recommendText: "Use examples/felidae_test_suite.fx as the current project-style test runner: it calls Felidae/Celidae, asserts output with str.contains, and records every case in one returned tuple."),
    content := str.concat(left: cards, right: guidance),
    return (HtmlRichSectionData(id: "testing", title: "Testing Felidae Programs", p: "Felidae tests should look like Felidae programs. Put the behavior under test in named facts and methods, call it from main(), and return a tuple that contains the case name, expected value, actual value, and status. This keeps tests readable by people and easy to run from automation.", p2: "Use two layers: pure unit-style checks inside the language for data transformations, and process-based smoke tests when you need to verify interpreter commands, imports, diagnostics, native modules, file I/O, or examples. felidae_debug should own syntax and AST diagnostic checks through --check-json.", content: content, code: "AssertEquals(name: string, expected: any, actual: any) =>\n    where expected == actual,\n    return (name: name, status: \"passed\", expected: expected, actual: actual)\nelse\n    return (name: name, status: \"failed\", expected: expected, actual: actual).\n\nAddTax(amount: number, rate: number) =>\n    return (amount + (amount * rate)).\n\nmain() =>\n    case1 := AssertEquals(name: \"adds tax\", expected: 110, actual: AddTax(amount: 100, rate: 0.10)),\n    case2 := AssertEquals(name: \"keeps zero tax\", expected: 80, actual: AddTax(amount: 80, rate: 0)),\n    failures := lambda([case1, case2], row => row.status == \"failed\"),\n    return (status: \"tested\", passed: count([case1, case2]) - count(failures), failed: count(failures), cases: [case1, case2]).", note: "Best practice: keep application examples and tests centered on main(). CLI queries are still supported, but main() is what docs, CI, felidae_debug checks, and users can repeat.", code2: "import (\"process\", \"str\").\n\nAssertContains(name: string, output: string, expected: string) =>\n    ok := str.contains(data: output, needle: expected),\n    where ok == \"true\",\n    return (name: name, status: \"passed\").\n\nRunCase(name: string, command: string, expected: string) =>\n    output := process.exec(command: command),\n    return (AssertContains(name: name, output: output, expected: expected)).\n\nmain() =>\n    docsCheck := RunCase(name: \"docs syntax\", command: \"build\\\\felidae_debug.exe docs\\\\server.fx --check-json\", expected: \"ok\"),\n    basics := RunCase(name: \"arithmetic example\", command: \"build\\\\felidae.exe examples\\\\arithmetic_and_boolean.fx\", expected: \"status\"),\n    return (status: \"smoke\", cases: [docsCheck, basics]).")).
