// Generated by tools/GenerateSentencePieceModel.cpp. Do not edit.
#pragma once

#include <cstdint>

namespace Felidae {
inline constexpr int kFelidaeBuiltinSentencePieceIds[] = {
    1, // import
    2, // not
    3, // and
    4, // or
    5, // then
    6, // if
    7, // else
    8, // return
    9, // where
    10, // extend
    11, // lambda
    12, // true
    13, // false
    14, // nil
    15, // (
    16, // )
    17, // {
    18, // }
    19, // [
    20, // ]
    21, // ,
    22, // :
    23, // .
    24, // |
    25, // ?
    26, // @
    27, // :=
    28, // ::
    29, // =>
    30, // +
    31, // -
    32, // *
    33, // /
    34, // %
    35, // ==
    36, // !=
    37, // <
    38, // <=
    39, // >
    40, // >=
};

namespace TokenId {
using Id = std::int32_t;
constexpr Id UNKNOWN = 0;
constexpr Id IMPORT = 1;
constexpr Id NOT = 2;
constexpr Id AND = 3;
constexpr Id OR = 4;
constexpr Id THEN = 5;
constexpr Id IF = 6;
constexpr Id ELSE = 7;
constexpr Id RETURN = 8;
constexpr Id WHERE = 9;
constexpr Id EXTEND = 10;
constexpr Id LAMBDA = 11;
constexpr Id TRUE = 12;
constexpr Id FALSE = 13;
constexpr Id NIL = 14;
constexpr Id LPAREN = 15;
constexpr Id RPAREN = 16;
constexpr Id LBRACE = 17;
constexpr Id RBRACE = 18;
constexpr Id LBRACKET = 19;
constexpr Id RBRACKET = 20;
constexpr Id COMMA = 21;
constexpr Id COLON = 22;
constexpr Id DOT = 23;
constexpr Id PIPE = 24;
constexpr Id QUESTION = 25;
constexpr Id AT = 26;
constexpr Id ASSIGN = 27;
constexpr Id DOUBLE_COLON = 28;
constexpr Id ARROW = 29;
constexpr Id PLUS = 30;
constexpr Id MINUS = 31;
constexpr Id STAR = 32;
constexpr Id SLASH = 33;
constexpr Id PERCENT = 34;
constexpr Id EQUAL = 35;
constexpr Id NOT_EQUAL = 36;
constexpr Id LESS = 37;
constexpr Id LESS_EQUAL = 38;
constexpr Id GREATER = 39;
constexpr Id GREATER_EQUAL = 40;
} // namespace TokenId
} // namespace Felidae
