if(NOT DEFINED FELIDAE_COMPILER OR NOT DEFINED FELIDAE_VM OR
   NOT DEFINED FELIDAE_EXAMPLE OR NOT DEFINED FELIDAE_BINARY_DIR)
    message(FATAL_ERROR "Felidae example test is missing a required path")
endif()

get_filename_component(FELIDAE_EXAMPLE_NAME "${FELIDAE_EXAMPLE}" NAME_WE)
set(FELIDAE_EXAMPLE_BINARY
    "${FELIDAE_BINARY_DIR}/${FELIDAE_EXAMPLE_NAME}.bin")

execute_process(
    COMMAND "${FELIDAE_COMPILER}" "${FELIDAE_EXAMPLE}"
    WORKING_DIRECTORY "${FELIDAE_BINARY_DIR}"
    RESULT_VARIABLE FELIDAE_COMPILE_RESULT
    OUTPUT_VARIABLE FELIDAE_COMPILE_OUTPUT
    ERROR_VARIABLE FELIDAE_COMPILE_ERROR)
if(NOT FELIDAE_COMPILE_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Compiler rejected ${FELIDAE_EXAMPLE}:\n${FELIDAE_COMPILE_OUTPUT}${FELIDAE_COMPILE_ERROR}")
endif()
if(NOT EXISTS "${FELIDAE_EXAMPLE_BINARY}")
    message(FATAL_ERROR
        "Compiler did not create ${FELIDAE_EXAMPLE_BINARY}:\n${FELIDAE_COMPILE_OUTPUT}")
endif()

execute_process(
    COMMAND "${FELIDAE_VM}" "${FELIDAE_EXAMPLE_BINARY}"
    WORKING_DIRECTORY "${FELIDAE_BINARY_DIR}"
    RESULT_VARIABLE FELIDAE_VM_RESULT
    OUTPUT_VARIABLE FELIDAE_VM_OUTPUT
    ERROR_VARIABLE FELIDAE_VM_ERROR)
if(NOT FELIDAE_VM_RESULT EQUAL 0)
    message(FATAL_ERROR
        "VM rejected ${FELIDAE_EXAMPLE_BINARY}:\n${FELIDAE_VM_OUTPUT}${FELIDAE_VM_ERROR}")
endif()
if(FELIDAE_VM_OUTPUT STREQUAL "")
    message(FATAL_ERROR "VM produced no result for ${FELIDAE_EXAMPLE}")
endif()

message(STATUS "${FELIDAE_EXAMPLE_NAME}: ${FELIDAE_VM_OUTPUT}")
